---
title: "Lab 00 - Hello IDS!"
author: "Lachlan Buchanan"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Peter Rabbit", "Lachlan", "Pearce", 
           "Bosh", ""),
  github_username = c("mcgregors-garden", "username 1", "username 2", 
                      "username 3", "username 4"), 
  colour = c("powderblue", "cornsilk", "orange", 
             "blue", "peachpuff4"),
  hobby = c("Hopping", "Walking", "Coding", 
            "Climbing", "Running"),
  favourite_number = c(2, 3, 5, 8, 9)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


*Bar chart displaying each Username and their favourite number*

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "Username", 
          y = "Favourite Number",
          title = "Bar chart for favourite numbers")
```

It is used to modify axis legend and plot labels on graph

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```


